export class LeadsPageLocators {
    static add_button = "//*[normalize-space(text())='Add']"
    static leads_title = "//fl-leads-list//*[normalize-space()='Leads']"
    static salutation_dropdown = "#lead_drawer_salutation_sel"
    static first_name_input = "#lead_drawer_first_name_txt"
    static last_name_input = "#lead_drawer_last_name_txt"
    static email_input = "#lead_drawer_email_txt"
    static phone_number_input = "#lead_drawer_phone_internal_txt"
    static employment_status_dropdown = "#lead_drawer_employment_status_sel"
    static monthly_income_input = "#lead_drawer_monthly_net_income_txt"
    static applying_alone_dropdown = "#lead_drawer_applying_alone_sel"
    static residency_status_dropdown = "#lead_drawer_resident_status_sel"
    static source_input = "[name='contact_id'] input"
    static external_id_input = "#lead_drawer_external_id_txt"
    static financing_type_dropdown = "[name='finance_type']"
    static capital_raising_amount_input = "#lead_drawer_capital_amount_needed_txt"
    static downpayment_input = "#lead_drawer_max_down_payment_txt"
    static property_value_input = "#lead_drawer_current_property_value_txt"
    static zip_input = "#lead_drawer_zip_txt"
    static save_as_application = "#lead_drawer_convert_btn"
    static send_email_button = "//mat-dialog-container//fl-button//*[contains(text(),'Send')]"
    static cancel_button = "//mat-dialog-container//fl-button//*[contains(text(),'Cancel')]"
    static lead_converted_message = "//*[normalize-space(text())='Lead was successfully converted']"
    static purchase_price_amount_input="#lead_drawer_purchase_price_txt"
    static found_property_dropdown ="#lead_drawer_found_property_sel"
    static property_type_dropdown ="#lead_drawer_property_type_sel"
    static real_estate_agent_fees ="#lead_drawer_real_estate_agent_fees_txt"
}